# Generated by Django 4.1.2 on 2022-10-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scanned_Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('article_id', models.TextField()),
                ('alcohol', models.TextField()),
                ('sellPrice', models.TextField()),
                ('averageRating', models.TextField()),
                ('maturity', models.TextField()),
                ('goesWithText', models.TextField()),
                ('goesWithText_de', models.TextField()),
                ('goesWithText_en', models.TextField()),
                ('goesWithText_fr', models.TextField()),
                ('goesWithText_it', models.TextField()),
                ('servingTemperature', models.TextField()),
                ('wineCharacter', models.TextField()),
                ('wineMaker', models.TextField()),
                ('wineOrigin', models.TextField()),
                ('yearOfVintage', models.TextField()),
                ('json', models.TextField()),
            ],
        ),
    ]
