# Generated by Django 4.1.2 on 2022-10-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop_challenge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scanned_Wine',
            new_name='ScannedWine',
        ),
    ]
