# Generated by Django 4.1.2 on 2022-10-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop_challenge', '0003_scannedwine_label_file_scannedwine_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedwine',
            name='alcohol',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='article_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='averageRating',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='goesWithText',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='goesWithText_de',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='goesWithText_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='goesWithText_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='goesWithText_it',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='maturity',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='sellPrice',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='servingTemperature',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='wineCharacter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='wineMaker',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='wineOrigin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scannedwine',
            name='yearOfVintage',
            field=models.TextField(blank=True),
        ),
    ]
