# Generated by Django 4.1.2 on 2022-10-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop_challenge', '0005_remove_scannedwine_label_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scannedwine',
            name='goesWithText_en',
        ),
    ]
